pub mod receiver;
pub mod sender;
mod packet_validator;
pub mod scheduler;
pub mod command;
pub mod uplink;
mod ground_service;
pub mod system_state;
pub mod fault_event;
pub mod program_utilization;
pub mod deadline_metrics;
pub mod jitter_metrics;